### PR TITLE
Routes setup

### LINKED ISSUE #1: refactor routes
issues
when trying to run server 
$ node server.ts
=> 
Node.js - SyntaxError: Unexpected token import in server.ts for import {IRoutes} from './routes/routes.interface'

- changed to require('')

then
2)
$ node server.ts
=> TypeError: Unknown file extension ".ts"  code: 'ERR_UNKNOWN_FILE_EXTENSION'

-changed to .js extension

then
3)
$ node server.js
=>  const RateExpressRoutes = require('./routes/rate'); require is not defined

-installed webpack and Browserify

### PR DESCRIPTION
**Pull request by ej2brown**
Added subroutes: index, group, rate, and user.

### CODE REVIEW

File: routes/dbHelpers/dbHelpers.ts [hunk 1]
```diff
@@ -1,17 +1,18 @@
 const bcrypt = require("bcrypt");
-import IQuery from "./interface"
+import type IQuery from "./interface"
 
-export class dbHelpersClass implements IQuery {
-  db: any;
+// export class dbHelpersClass implements IQuery {
+module.exports = db => {
```
Comment (thecameraguy) [inline routes/dbHelpers/dbHelpers.ts:5]: Let's move the whole content of this file into PostgresController.ts

Let's make PostgresController implement IDatabaseController and implement the methods that are defined in this interface.

The methods should correspond exactly to the functions you've defined in this file.

So let's move addUser function's code into PostgresController's addUser method (see IDatabaseController defining the addUser method).

And do the same for every function that's in this file.

After that, we will have to import PostgresController into server.ts and instantiate it and pass it into the routes exactly like how the dbHelper is being passed in.

File: routes/group.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 import { AbstractExpressRoutes } from "./expressRoutes";
-const dbHelpersClass = require("./dbHelpers/dbHelpers.ts");
+const dbHelpersClass = require("./dbHelpers/dbHelpers");
 
 export class GroupExpressRoutes extends AbstractExpressRoutes {
   private m_dbHelpers: any;
```
Comment (thecameraguy) [inline routes/group.ts:5]: this will need to be typed as IDatabaseController since we want to refactor dbHelper into PostgresController :)

Also we want to change the db: any from the constructor's arguments list into db: IDatabaseController. 

After that, we won't need to do `this.m_dbHelpers = dbHelperClass(db)`, we will just need to do `this.m_dbHelpers = db`

File: routes/group.ts [hunk 3]
```diff
@@ -1,5 +1,5 @@
 import { AbstractExpressRoutes } from "./expressRoutes";
-const dbHelpersClass = require("./dbHelpers/dbHelpers.ts");
+const dbHelpersClass = require("./dbHelpers/dbHelpers");
```
Comment (thecameraguy) [inline routes/group.ts]: We won't need this anymore since we are factoring out dbHelpers into PostgresController.

We will need to import IDatabaseController though.

File: routes/index.ts [hunk 4]
```diff
@@ -1,5 +1,5 @@
 import { AbstractExpressRoutes } from "./expressRoutes";
-const dbHelpersClass = require("./dbHelpers/dbHelpers.ts");
+const dbHelpersClass = require("./dbHelpers/dbHelpers");
```
Comment (thecameraguy) [inline routes/index.ts]: Same set of changes for all the other routes!!

File: server-src/server.ts [hunk 5]
```diff
@@ -18,6 +18,15 @@ const PORT = 3001
...
 
+// const webpack = require('webpack');
+// const webpackDevMiddleware = require('webpack-dev-middleware');
+// const config = require('./webpack.config.js');
+// const compiler = webpack(config);
+
+// app.use(webpackDevMiddleware(compiler, {
+//   publicPath: config.output.publicPath,
+// }));
+
```
Comment (thecameraguy) [inline server-src/server.ts:31]: After factoring out dbHelper into PostgresController, we will need to instantiate it here via `const dbController: IDatabaseController = new PostgresController (db);` Here, db is the Pool object you create already.

We will need to pass in this into routes like `new IndexExpressRoutes('/', dbController);`

File: src/database/postgres/postgresController.ts [hunk 6]
```diff
@@ -0,0 +1,235 @@
...
+ * In this loop, when cat is HouseCat object, it calls HouseCat scratch() method. When cat is MaineCoon object, it calls MaineCoon scratch() method.
+ * 
+ * The mechanism that allows us to have a collection of superclass who are comprised of various subclasses whose methods are called depending on the
+ * subclass type is called "Polymorphism". Now we know the final and perhaps the most important fundemantal mechanism of OOP. "Polymorphsm". 
+ * 
+ * Polymorphism allows us to reduce duplicating code and share a set of behaviour that can be used and modified based which class is being used in the code!
+ * 
+ */
+
+// Implement IDatabaseController here.
```
Comment (thecameraguy) [inline src/database/postgres/postgresController.ts:522]: We want to implement IDatabaseController as PostgresController class here. It will have a list of methods that corresponds 1:1 to the functions you have in dbHelpers. See the IDatabaseController interface for the list of methods that need to be implemented.

File: routes/group.ts (hunk 2 above)
Comment (ej2brown) [reply routes/group.ts:5]: If I'm passing postgresController into server.ts which exports it into the routes, do I still need to import IDatabaseController?

File: routes/dbHelpers/dbHelpers.ts (hunk 1 above)
Comment (ej2brown) [reply routes/dbHelpers/dbHelpers.ts:5]: okay done!

File: server-src/server.ts (hunk 5 above)
Comment (ej2brown) [reply server-src/server.ts:31]: Just saw this! Did something similar but I'll use this instead

File: routes/group.ts (hunk 2 above)
Comment (thecameraguy) [reply routes/group.ts:5]: I didn't know ts export worked this way.. does it work if you don't have import there??
To my knowledge it needs to be imported in every file that uses a particular class/interface. I could be wrong.

File: src/database/postgres/postgresController.ts [hunk 7]
```diff
@@ -0,0 +1,522 @@
...
+      throw new Error('Cannot access db'); 
+  }
+    this.m_db = db;
+  }
+
+  public get db(): any {
+    return this.m_db;
+}
+  /* For ../user.ts */
+  addUser(user: any) {
```
Comment (thecameraguy) [inline src/database/postgres/postgresController.ts]: for all of the methods, we should either specify public, protected, private.
In our case, all of these methods that we implement from the interface should be public.

Let's specify explicitly that these methods are public by writing public addUser(...)

File: src/database/postgres/postgresController.ts [hunk 8]
```diff
@@ -0,0 +1,522 @@
...
+  private m_db: any;
+
+  constructor(db: any) {
+    if (db === null || db === void 0) {
+      throw new Error('Cannot access db'); 
+  }
+    this.m_db = db;
+  }
+
+  public get db(): any {
```
Comment (thecameraguy) [inline src/database/postgres/postgresController.ts:15]: Nice use of property!!

File: routes/group.ts [hunk 9]
```diff
@@ -1,12 +1,12 @@
 import { AbstractExpressRoutes } from "./expressRoutes";
-const dbHelpersClass = require("./dbHelpers/dbHelpers.ts");
+// const IDatabaseController = require("./dbHelpers/dbHelpers");
 
 export class GroupExpressRoutes extends AbstractExpressRoutes {
   private m_dbHelpers: any;
 
   constructor(baseEndpoint: string, db: any) {
```
Comment (thecameraguy) [inline routes/group.ts]: Let's type db as IDatabaseController

**Comment by thecameraguy** [comment]
@ej2brown I have couple more comments and the code should be good to go after they are addressed!

**Comment by thecameraguy** [comment]
Oh, also, generally, we shouldn't commit anything under dist folder - this gets auto-generated by build.

File: src/database/postgres/postgresController.ts (hunk 8 above)
Comment (ej2brown) [reply src/database/postgres/postgresController.ts:15]: haha used your codes as reference!

File: routes/group.ts (hunk 2 above)
Comment (ej2brown) [reply routes/group.ts:5]: I'll add them, I think you're right

File: routes/group.ts [hunk 10]
```diff
@@ -1,12 +1,12 @@
 import { AbstractExpressRoutes } from "./expressRoutes";
-const dbHelpersClass = require("./dbHelpers/dbHelpers.ts");
+import { IDatabaseController } from '../src/database/databaseController.interface';
 
 export class GroupExpressRoutes extends AbstractExpressRoutes {
   private m_dbHelpers: any;
```
Comment (thecameraguy) [inline routes/group.ts:5]: one last thing! This should be typed IDatabaseController

**Comment by thecameraguy** [comment]
👍 after the one last simple miss! Merge away after this! 🎉 🎉 @ej2brown

**Comment by thecameraguy** [comment]
@ej2brown Now, for OOP exercise, think about what you'd do if you want to switch your database from postgres to something else - mysql or mongodb. Which classes would you create? How would you pass it along to the routes? Do routes classes need modification at all?

The answer to the last question is: Nope: the whole point of declaring the interface and having routes reference only to the IDatabaseController interface is that the routes would be agnostic to the implementation details of the database controllers. You can pass in a class that implements the details for postgres and it will work. Same story if you pass in a class that implements the details for mysql or mongo db.

File: routes/group.ts (hunk 10 above)
Comment (ej2brown) [reply routes/group.ts:5]: Done!

**Comment by thecameraguy** [comment]
@ej2brown merge away!!! 🚢
